"""Pydantic input/output contracts for the EcoRoute MCP tools.

These models are the frozen interface between the protocol layer
(server.py) and the math engine (calculator.py) -- Milestone 1 of the
project plan. FastMCP derives each tool's JSON-RPC schema from the
annotations here, so changing a field changes the wire contract.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

# --- Shared parameter annotations -------------------------------------------------

PromptTokens = Annotated[
    int, Field(ge=0, le=10_000_000, description="Tokens in the input context (prefill phase).")
]
CompletionTokens = Annotated[
    int, Field(ge=0, le=10_000_000, description="Tokens generated by the model (decode phase).")
]
RegionId = Annotated[
    str,
    Field(
        min_length=1,
        description="Region id from list_datacenter_regions, e.g. 'us-east-va'.",
    ),
]
HardwareId = Annotated[
    str, Field(min_length=1, description="Accelerator id, e.g. 'H100' or 'A100'.")
]
ModelParamsB = Annotated[
    float,
    Field(gt=0, le=100_000, description="Dense model size in billions of parameters."),
]
MaxLatencyMs = Annotated[
    int,
    Field(gt=0, le=60_000, description="Round-trip latency budget the routing decision must respect."),
]


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid")


# --- Tool outputs -----------------------------------------------------------------


class FootprintResult(_Strict):
    """Energy, carbon and water cost of one inference request in one region."""

    region: str
    region_name: str
    hardware: str
    model_params_b: float
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int

    energy_kwh: float = Field(description="Facility energy including PUE overhead.")
    it_energy_kwh: float = Field(description="Accelerator energy before cooling overhead.")
    overhead_energy_kwh: float = Field(description="Cooling/distribution overhead from PUE.")
    prefill_joules: float
    decode_joules: float

    carbon_g_co2eq: float = Field(description="Operational emissions in grams CO2-equivalent.")
    water_liters: float = Field(description="Evaporative cooling water loss in liters.")

    pue: float
    carbon_intensity_g_per_kwh: float
    wue_l_per_kwh: float


class RankedRegion(_Strict):
    rank: int
    region: str
    carbon_g_co2eq: float
    energy_kwh: float
    water_liters: float
    latency_ms: int


class ExcludedRegion(_Strict):
    region: str
    latency_ms: int
    reason: str


class RoutingDecision(_Strict):
    """Ranked routing recommendation under a latency constraint."""

    recommended_region: str
    recommended_region_name: str
    latency_ms: int
    carbon_g_co2eq: float
    energy_kwh: float
    water_liters: float

    baseline_region: str
    baseline_carbon_g_co2eq: float
    carbon_saved_g_co2eq: float
    carbon_reduction_pct: float
    water_reduction_pct: float

    ranking: list[RankedRegion]
    excluded_regions: list[ExcludedRegion]


class RegionProfile(_Strict):
    id: str
    name: str
    corridor: str
    cloud_region: str
    dominant_sources: list[str]
    carbon_intensity_g_per_kwh: float
    pue: float
    wue_l_per_kwh: float
    baseline_latency_ms: int


class AcceleratorProfile(_Strict):
    id: str
    name: str
    tdp_watts: float
    peak_flops_bf16: float
    prefill_flops_per_joule: float
    decode_flops_per_joule: float


class RegionCatalog(_Strict):
    regions: list[RegionProfile]
    accelerators: list[AcceleratorProfile]
